import requests
import os

USERNAME = "Pace-Runner"
TOKEN = os.environ.get("GH_TOKEN", "")

headers = {"Authorization": f"token {TOKEN}"} if TOKEN else {}

# ── Category rules ───────────────────────────────────────────────────────────
# Map repo names (lowercase) to a section. Anything not listed falls into
# "Other Projects". Add new repos here whenever you want them categorised.
CATEGORIES = {
    "finance": [
        "nas100-trading-bot",
        "sp500-valuation-analysis",
        "iv-surface-and-recovery-theorem-plot",
        "analyticclarity.com",
    ],
    "software": [
        "surrogate-shopper",
        "-snake-ai",
    ],
    "algorithms": [
        "maze-solver-bfs-approach-",
        "16x16-sudoku-solver-optimized-backtracking-with-heuristics-",
        "graph-coloring-in-java",
    ],
    "cybersecurity": [
        "aws-iam-access-control-project",
    ],
}

SECTION_META = {
    "finance":       ("📊", "Finance"),
    "software":      ("💻", "Software"),
    "algorithms":    ("⚙️",  "Algorithms"),
    "cybersecurity": ("🔐", "Cybersecurity"),
}

def fetch_repos():
    url = f"https://api.github.com/users/{USERNAME}/repos?per_page=100&type=public"
    resp = requests.get(url, headers=headers)
    resp.raise_for_status()
    return resp.json()

def categorise(repos):
    buckets = {k: [] for k in CATEGORIES}
    buckets["other"] = []

    for repo in repos:
        if repo.get("fork"):
            continue  # skip forks
        name_lower = repo["name"].lower()
        matched = False
        for cat, names in CATEGORIES.items():
            if name_lower in names:
                buckets[cat].append(repo)
                matched = True
                break
        if not matched:
            buckets["other"].append(repo)

    return buckets

def repo_row(repo):
    name = repo["name"]
    url  = repo["html_url"]
    desc = repo.get("description") or "—"
    lang = repo.get("language") or "—"
    return f"| [{name}]({url}) | {desc} | {lang} |"

def build_section(cat, repos):
    if not repos:
        return ""
    emoji, title = SECTION_META.get(cat, ("📁", cat.title()))
    lines = [
        f"## {emoji} {title}",
        "",
        "| Repo | Description | Language |",
        "|------|-------------|----------|",
    ]
    for repo in sorted(repos, key=lambda r: r["name"].lower()):
        lines.append(repo_row(repo))
    lines.append("")
    return "\n".join(lines)

def generate():
    repos   = fetch_repos()
    buckets = categorise(repos)

    sections = []
    for cat in ["finance", "software", "algorithms", "cybersecurity"]:
        s = build_section(cat, buckets[cat])
        if s:
            sections.append(s)

    if buckets["other"]:
        s = build_section("other", buckets["other"])
        sections.append(s.replace("## 📁 Other", "## 📁 Other Projects"))

    readme = f"""# Hi, I'm Owen Pace 👋

Computer Science student with a passion for algorithms, AI, and quantitative finance.
I enjoy building things that solve real problems — from mobile apps to trading bots.

---

## About me

- 🎓 Studying Computer Science
- 🧠 Interested in algorithms, AI agents, and financial modelling
- 📈 Building algorithmic trading systems and market analysis tools
- 🔐 CTF participant — enjoy low-level security challenges

---

{chr(10).join(sections)}
---

## Connect

- 🔗 LinkedIn: [paste link here]
- ✉️ Email: [paste address here]
- 🌐 Website: [paste link here]

---

*This README is auto-generated by [generate_readme.py](generate_readme.py) via GitHub Actions.*
"""

    with open("README.md", "w") as f:
        f.write(readme)
    print("README.md generated successfully.")

if __name__ == "__main__":
    generate()
